# Generated by Django 4.1.2 on 2022-10-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=False)),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=9, null=False)),
                ('descricao', models.TextField(null=False)),
                ('foto', models.URLField(max_length=255, null=False)),
            ],
        ),
    ]
